export function buildMarkdownString({ appSummary, analysis, testCategories, results = {}, failureNotes = {}, brief }) {
  const allCases = (testCategories || []).flatMap(c => c.cases || []);
  const passed   = allCases.filter(tc => results[tc.id] === "pass").length;
  const failed   = allCases.filter(tc => results[tc.id] === "fail").length;
  const untested = allCases.filter(tc => !results[tc.id]).length;
  const total    = allCases.length;
  const passRate = total > 0 ? Math.round((passed / total) * 100) : 0;
  const date     = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  const lines = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push("# QA Report");
  lines.push(`_Generated by QA Copilot · ${date}_`);
  lines.push("");

  // ── App info ────────────────────────────────────────────────────────────────
  if (appSummary) {
    lines.push("## App Info");
    lines.push("");
    appSummary.split("\n").forEach(line => {
      const [key, ...rest] = line.split(":");
      if (rest.length) lines.push(`**${key.trim()}:** ${rest.join(":").trim()}`);
    });
    lines.push("");
  }

  // ── Summary stats ────────────────────────────────────────────────────────────
  lines.push("## Results Summary");
  lines.push("");
  lines.push(`| Total | Passed | Failed | Untested | Pass Rate |`);
  lines.push(`|-------|--------|--------|----------|-----------|`);
  lines.push(`| ${total} | ${passed} | ${failed} | ${untested} | ${passRate}% |`);
  lines.push("");

  // ── Risk analysis ────────────────────────────────────────────────────────────
  if (analysis) {
    lines.push("## Risk Analysis");
    lines.push("");
    lines.push(`**Risk Level:** ${analysis.severity}`);
    if (analysis.severity_reason) lines.push(`_${analysis.severity_reason}_`);
    lines.push("");
    if (analysis.summary) lines.push(analysis.summary);
    lines.push("");

    if (analysis.top_risks?.length) {
      lines.push("### Top Risks");
      lines.push("");
      analysis.top_risks.forEach(r => {
        lines.push(`#### ${r.emoji || "⚠️"} ${r.title}${r.likelihood ? ` · ${r.likelihood} Risk` : ""}`);
        if (r.detail)    lines.push(r.detail);
        if (r.impact)    lines.push(`> **Impact:** ${r.impact}`);
        if (r.fix_hint)  lines.push(`> **Fix:** ${r.fix_hint}`);
        lines.push("");
      });
    }

    if (analysis.probably_missed?.length) {
      lines.push("### Things You Probably Haven't Tested");
      lines.push("");
      analysis.probably_missed.forEach(item => lines.push(`- ${item}`));
      lines.push("");
    }

    if (analysis.quick_wins?.length) {
      lines.push("### Quick Wins");
      lines.push("");
      analysis.quick_wins.forEach(item => lines.push(`- ${item}`));
      lines.push("");
    }
  }

  // ── Test results ─────────────────────────────────────────────────────────────
  if (testCategories?.length) {
    lines.push("## Test Results");
    lines.push("");
    testCategories.forEach(cat => {
      if (!cat.cases?.length) return;
      lines.push(`### ${cat.icon} ${cat.label}`);
      lines.push("");
      cat.cases.forEach(tc => {
        const res = results[tc.id];
        const icon = res === "pass" ? "✅" : res === "fail" ? "❌" : "⬜";
        lines.push(`#### ${icon} ${tc.id} — ${tc.title}`);
        lines.push(`_${tc.importance}${tc.category ? ` · ${tc.category}` : ""}_`);
        if (tc.starting_point) lines.push(`**Start on:** ${tc.starting_point}`);
        if (tc.steps?.length) {
          lines.push("");
          tc.steps.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
        }
        if (tc.what_good_looks_like) lines.push(`\n**Should see:** ${tc.what_good_looks_like}`);
        if (tc.what_bad_looks_like) lines.push(`**Bug looks like:** ${tc.what_bad_looks_like}`);
        if (res === "fail" && failureNotes[tc.id]) {
          lines.push(`\n> **Observed:** ${failureNotes[tc.id]}`);
        }
        lines.push("");
      });
    });
  }

  // ── Automation brief ─────────────────────────────────────────────────────────
  if (brief) {
    lines.push("## Automation Brief");
    lines.push("");
    if (brief.verdict) lines.push(brief.verdict);
    lines.push("");

    const section = (title, items) => {
      if (!items?.length) return;
      lines.push(`### ${title}`);
      lines.push("");
      items.forEach(item => lines.push(`- **${item.id}** ${item.title} — ${item.reason}`));
      lines.push("");
    };

    section("Worth Automating", brief.automate);
    section("Keep Manual", brief.keep_manual);
    section("Skip for Now", brief.skip_for_now);

    if (brief.cursor_prompt) {
      lines.push("### Cursor / Claude Code Prompt");
      lines.push("");
      lines.push("```");
      lines.push(brief.cursor_prompt);
      lines.push("```");
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(`_QA Copilot · ${date}_`);

  return lines.join("\n");
}

export function generateMarkdownReport(data) {
  const content = buildMarkdownString(data);
  const blob    = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url     = URL.createObjectURL(blob);
  const a       = document.createElement("a");
  a.href        = url;
  a.download    = `qa-report-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
